### ISSUE TITLE
Needs a easter egg

### ISSUE THREAD

**Issue by ghost** [RayBytes/minehut-file-watcher#1]
It's a cultural religion to add secret easter eggs in code, do it or else we'll process.exit(1) you!

**Comment by RayBytes** [comment]
> It's a cultural religion to add secret easter eggs in code, do it or else we'll process.exit(1) you!

hmmm, what do you suggest. I dont want to be process exit'd 😢

**Comment by ghost** [comment]
Something along the lines of ‘we are watching you’ to mess with people

**Comment by ghost** [comment]
Or something cheesy

**Comment by RayBytes** [comment]
> Something along the lines of ‘we are watching you’ to mess with people

hmmm

**Comment by RayBytes** [comment]
> It's a cultural religion to add secret easter eggs in code, do it or else we'll process.exit(1) you!

awokens give me one of your quirky reddit comments you post it in the minehut discord

**Comment by ghost** [comment]
doritos.

**Comment by RayBytes** [comment]
> doritos.

Issue fixed
